# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WKViewManagerDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
 pod "Masonry"
  # Pods for WKViewManagerDemo

  target 'WKViewManagerDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WKViewManagerDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
